---
title: "mail-in_votes"
author: "ymysherry"
date: "12/4/2020"
output: github_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(rvest)
library(patchwork)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Comparison of both candidates' mail-in votes

#Compare the number of mail-in ballots of dem/rep in each state

```{r}
returnedballots_df =
  read_csv("data/mail_in.csv") %>% 
  select(state, party, returned_ballots) %>% 
  filter(party %in% c("Democrats", "Republicans")) %>%
  group_by(state, party) 
 

plot_returned_ballots = 
  returnedballots_df %>%
  ggplot(aes(x = state, y = returned_ballots, fill = party)) +
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(
  title = "The number of returned mail-in ballots of each party by state",
  x = "State",
  y = "Number of returned mail-in ballots",
  caption = "Data from 'https://electproject.github.io/Early-Vote-2020G/'"
  )
  

```

#Compare the return rate of mail-in ballots for each party by state
```{r}
returnrate_df =
  read_csv("data/mail_in.csv") %>% 
  select(state, party, return_rate) %>% 
  filter(party %in% c("Democrats", "Republicans")) %>%
  group_by(state, party) 
 

plot_return_rate = 
  returnrate_df %>%
  ggplot(aes(x =return_rate, y = state, fill = party)) +
  geom_bar(stat="identity", position=position_dodge()) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(
  title = "The return rate of mail-in ballots for each party by state",
  x = "Return rate of mail-in ballots",
  y = "State",
  caption = "Data from 'https://electproject.github.io/Early-Vote-2020G/'"
  )
  

```

```{r}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```