---
title: "Final Project Proposal"
date: "11/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Group members
Ziyin Lu (zl2861), Yuanming Mao (ym2770), Yike Zhao (yz3738), 


## Tentative project title
Presidential Election in Pandemic


## Motivation
The COVID-19 pandemic, the economy, and racial injustice have been top concerns in the 2020 presidential election. According to AP VoteCast, a national survey of the electorate, about 4 in 10 voters suggest the pandemic as the top issue while the economy follows behind. However, an Associated Press analysis gave conclusions with a surprising twist: in counties with worst COVID-19 surges, Trump enjoyed enormous support. We are interested in using polling data and data of the COVID-19 case incidence / death rates to investigate whether and how COVID-19 pandemic has influenced supporting rate distribution among all states, particularly in top battlegrounds.


## The intended final products
A website that includes a report of our exploratory analyses, regression analysis and visualization, and an interactive dashboard.


## The anticipated data sources
* [RealClearPolitics](https://www.realclearpolitics.com/)

* [An github election project](https://electproject.github.io/)

* [COVID-19 data by states](https://www.realclearpolitics.com/coronavirus/country/united-states/)


## Analyses
1. Analyses of key states / top battlegrounds (eg: Florida, Pennsylvania, Michigan, Wisconsin, North Carolina, Arizona, Ohio, Minnesota, Iowa, Nevada, Texas, Georgia, Virginia, New Hampshire, Maine, Colorado and New Mexico)
  a. Time trend & regression of supporting rate poll in 2020 and COVID-19 confirm/death rate, startidied by states.
  b. Comparison of democratic / republican supporting rate between 2020 and 2016
  c. Supporting rate distribution among mail-in ballots.
  
2. Analyses of all states:
  a. Compare the COVID-19 death / confirmed case rate distribution in blue and red states.
  b. Voting rate vs. COVID-19 death rate distribution. 


## Visualization:
1. 3 Linear graphs representing the change of supporting rate of democratic and republican, and the COVID-19 confirmed/death rate respectively on the same panel
2. Histograms showing the supporting rate of democratic in 2020 and 2016 and it of repulbican in 2020 and 2016
3. Pie plot showing the distribution of democratic and republican among the mail-in ballots in 2020
4. Box plot comparing the COVID-19 death / confirmed case among red states and blue states respectively
5. Histograms showing the voting rate and COVID-19 death rate in each state respectively.


## The planned analyses / visualizations / coding challenges
1. Mail-in ballots (nearly half of the votes) at some of the pivotal states have not yet been counted. No winner has been declared in this presidential election. Pre-election day polling statistics could be confusing as some of the voters do not participate in these polls.

2. The comparison of supporting rates of both candidates between 2016 and 2020's election could be significantly different, because the number of voters in 2020 are significantly higher than in 2016. Sampling population in both years would not be representative enough to complete the comparative analysis.

3. Test-positive rate and case-fatality rate for Covid-19 over time is influenced by the seasonal fluctuation and also vary by age groups, since older people are more likely to be infected; In addition, more testing kits are becoming  available after FEMA and state governments started to purchase them. 



